---
- name: Deploy Angular app
  hosts: all
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Create web directory
      file:
        path: /var/www/html/olympic-games-starter
        state: directory
        mode: '0755'

    - name: Copy Angular app
      copy:
        src: app/olympic-games-starter/
        dest: /var/www/html/olympic-games-starter/

    - name: Deploy nginx config
      copy:
        src: nginx/app.conf
        dest: /etc/nginx/sites-available/default
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted